# Generated by Django 2.2.1 on 2019-12-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(verbose_name='celery任务id')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='主机ip')),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'up'), (2, 'down')], default=1, verbose_name='主机状态')),
                ('scan_status', models.IntegerField(choices=[(0, '待探测'), (1, '正在探测'), (2, '探测成功'), (3, '探测失败')], default=0, verbose_name='主机探测状态')),
            ],
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=32, verbose_name='机房简称')),
                ('idc_name_all', models.CharField(max_length=32, verbose_name='机房全称')),
                ('address', models.CharField(max_length=64, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=11, verbose_name='机房电话')),
                ('name', models.CharField(max_length=32, verbose_name='机房联系人姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='TasksOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=36, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(null=True, verbose_name='扫描开发的端口号')),
                ('iamge', models.CharField(max_length=256, null=True, verbose_name='截图之后图片路径')),
                ('celeryinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.CeleryInfo')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Host')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.TasksOrder')),
            ],
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='登陆密码')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Idc'),
        ),
    ]
