# Generated by Django 2.2.1 on 2019-12-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='idc',
        ),
        migrations.AddField(
            model_name='host',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Company'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Idc',
        ),
    ]
