# Generated by Django 2.2.1 on 2019-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20191230_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryinfo',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
