# Generated by Django 2.2.1 on 2019-12-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_celeryinfo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksorder',
            name='celeryinfo',
            field=models.IntegerField(null=True, verbose_name='CeleryInfo表的id'),
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=32, verbose_name='端口')),
                ('state', models.CharField(max_length=32, verbose_name='状态')),
                ('reason', models.TextField(verbose_name='原因')),
                ('extrainfo', models.TextField(verbose_name='额外信息')),
                ('name', models.TextField(verbose_name='名字')),
                ('version', models.TextField(verbose_name='版本')),
                ('product', models.TextField(verbose_name='产品')),
                ('cpe', models.TextField(verbose_name='CPE')),
                ('script', models.TextField(verbose_name='脚本')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Host')),
                ('task_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.TasksOrder')),
            ],
        ),
    ]
