# Generated by Django 2.2.1 on 2019-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20191231_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksorder',
            name='celeryinfo',
        ),
        migrations.AddField(
            model_name='tasksorder',
            name='celeryinfoid',
            field=models.IntegerField(default=0, verbose_name='CeleryInfo表的id'),
        ),
    ]
