# Generated by Django 2.2.1 on 2019-12-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20191231_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksorder',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.Host'),
            preserve_default=False,
        ),
    ]
