# Generated by Django 2.2.1 on 2019-12-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_tasksorder_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='iamge',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='celeryinfo',
        ),
    ]
