# Generated by Django 2.2.1 on 2019-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20191231_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='percent',
            field=models.FloatField(default=0, verbose_name='相似概率'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='simple_image',
            field=models.CharField(max_length=256, null=True, verbose_name='相似图片路径'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.IntegerField(default=0, verbose_name='图片状态'),
        ),
    ]
